apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-init
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Prithviraj2003/gitops-apps.git
    targetRevision: main
    path: argocd/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true